### PR TITLE
Updates from make generate

### PR DESCRIPTION
**Pull request by jmoldow**
Signed-off-by: Jordan Moldow <jmoldow@alum.mit.edu>

### CODE REVIEW

**Comment by jmoldow** [comment]
The missing update in https://github.com/jmoldow/vitess-operator/blob/make-generate/pkg/apis/planetscale/v2/zz_generated.deepcopy.go#L2551 seems particularly problematic. That might be a bug in versions of the operator since that config was introduced. It'd be great to have all files kept up-to-date with each PR, but at least the yaml files being out-of-date won't cause the operator to misbehave, but out-of-date generate code might be fatal.

Could y'all consider adding a new Github workflow check, to prevent merges/releases if the generated files are out-of-date?

I've done something like this in some of my own projects that have code generation:

```bash
make generate
git add --all
git diff HEAD
echo 'If this test fails, it is because the git diff is non-empty after running "make generate".'
echo 'This indicates that either:'
echo ' - A source change has been made without running "make generate" and committing the corresponding generated code.'
echo ' - A manual change has been made to an auto-generated file, which is not supported or allowed.'
echo 'See the diff above for more information.'
echo 'To correct this, locally run "make generate", commit the changes, and re-run tests.'
git diff HEAD --quiet --exit-code
```

@dctrwatson @skottler 

I can submit that in a separate PR for your consideration.

**Comment by jmoldow** [comment]
Added a proposal for that automated check in #209 .

**Comment by skottler** [comment]
LGTM. Added @jordw for additional review.

**Review by skottler — APPROVED** [review]

**Comment by jmoldow** [comment]
@skottler @jordw Can we merge this now?

**Review by jordw — APPROVED** [review]

**Comment by jordw** [comment]
@jmoldow Sorry I was out of the office

**Comment by jmoldow** [comment]
Thanks for approving @jordw . I don't have merge abilities, could someone do that for me? @skottler @jordw ?

**Comment by jordw** [comment]
Done!

**Pull request merged**
