### PR TITLE
Add forcePathStyle setting for S3 backup

### PR DESCRIPTION
**Pull request by L3o-pold**
Could be a better idea to add support for vttablet `extraFlags` .

### CODE REVIEW

**Comment by deepthi** [comment]
Is the issue that vttablet supports `extraFlags` but they are not used by the `vitessbackup` object?

**Comment by L3o-pold** [comment]
Main issue is that we can't set the `forcePathStyle` settings. A way to fix this is to do as I did in the PR.

An other way to fix the issue (and in a more durable and flexible way) could be to as you said use `extraFlags` in a `vitessbackup`.

**Review by dctrwatson — APPROVED** [review]
This seems like a straightforward/simple solution to the issue.

I agree adding `ExtraFlags` would be more flexible; just it would need to be added to each backup location type + methods.

**Comment by L3o-pold** [comment]
I rebase my changes if we can move forward with this.

**Comment by deepthi** [comment]
> I rebase my changes if we can move forward with this.

Yes, please

**Comment by L3o-pold** [comment]
> > I rebase my changes if we can move forward with this.
> 
> Yes, please

done

**Pull request merged**
