### PR TITLE
Revert "Set vttablet init container resource limits"

### PR DESCRIPTION
**Pull request by nickvanw**
Reverts planetscale/vitess-operator#216

This is causing issues (https://github.com/planetscale/vitess-operator/issues/240), let's revert it for now and we can figure out what the solution is. 

cc @deepthi & @aquarapid

### CODE REVIEW

**Review by deepthi — APPROVED** [review]

**Comment by deepthi** [comment]
@brandt we have to revert #216 until #240 can be fixed.
Would you be able to do another PR that can get you what you need without breaking the case in #240?

**Comment by brandt** [comment]
Ah, I see in `update.ResourceRequirements(dst, src)` an undefined limit in `src` will not overwrite a defined limit in `dst`. 

This should be fixable by simply removing the default limit on the init container. If the cluster requires a limit to be set, the user will have to have already defined it on the vttablet container, and the init container limit will be automatically updated to use the same value. If the vttablet limit is _not_ set, the init container limit will remain unset as well.

Does that sound like a reasonable approach?

**Comment by deepthi** [comment]
@dctrwatson can you comment on the proposed fix?

**Comment by dctrwatson** [comment]
> Does that sound like a reasonable approach?

> @dctrwatson can you comment on the proposed fix?

Ah ya, that sounds like it would be a workable fix.

**Pull request merged**
