### PR TITLE
Add 'make generate-and-diff'

### PR DESCRIPTION
**Pull request by jmoldow**
Add a new Makefile target that will exit with a failure if
'make generate' generates any changes from what is currently
committed.

Use this in a new Github workflow, to reject PRs that should
include changes to generated files, but haven't generated and
committed those changes yet.

Update CRDs from pull #207

Update docs and generated code from pull #207

Signed-off-by: Jordan Moldow <jmoldow@alum.mit.edu>

### CODE REVIEW

**Comment by jmoldow** [comment]
This new check is able to correctly detect and block on the missing generated code that is being fixed in #208 @dctrwatson @skottler

**Review by skottler — APPROVED** [review]
LGTM 🙇

**Comment by skottler** [comment]
We can hold this until #208 gets merged so that there aren't failing checks against main.

**Comment by jmoldow** [comment]
@skottler Can this be merged?

**Pull request merged**
