### PR TITLE
pkg/apis/planetscale/v2: fix VitessKeyRange rounding logic

### PR DESCRIPTION
**Pull request by mdlayher**
Fixes a rounding error discovered while creating a keyspace with 6 shards.

/cc @deepthi @planetscale/eng-vitess

### CODE REVIEW

**Review by Verolop — APPROVED** [review]

**Comment by GuptaManan100** [comment]
@mdlayher could you merge main into your PR. The test failures have been fixed in https://github.com/planetscale/vitess-operator/pull/270

**Comment by mdlayher** [comment]
@GuptaManan100 rebase complete!

**Comment by GuptaManan100** [comment]
@mdlayher there is another rebase required. Apologies for that.

**Comment by mdlayher** [comment]
@GuptaManan100 no problem, I believe it's all set now.

**Review by GuptaManan100 — APPROVED** [review]
Thankyou! This is a great catch!

**Pull request merged**
