### PR TITLE
Update PodDisruptionBudget to policy/v1

### PR DESCRIPTION
**Pull request by joneug**
policy/v1beta1 is deprecated in v1.21.0+ and
unavailable in v1.25+.

### CODE REVIEW

**Comment by GuptaManan100** [comment]
The changes look good to me, but the integration-test seem to be failing consistently.

**Comment by Verolop** [comment]
@GuptaManan100 `signal:killed` might indicate that the test is running out of memory.  Looking for options.

**Review by Verolop — APPROVED** [review]
LGTM (tests pending)

**Review by frouioui — APPROVED** [review]
This is looking good to me. I'll monitor the CI status after merging main into this branch.

**Comment by Areso** [comment]
Guys, as 1.25 getting more wide presence, this problem should get more attention.

**Comment by de-metavision** [comment]
any updates on this PR? I have been testing this branch with k8s v1.25 and it seems to be working well. 
I would really love to see this merged and released soon.

**Comment by frouioui** [comment]
Closing this Pull Request, the issue will be resolved by https://github.com/planetscale/vitess-operator/pull/397#pullrequestreview-1347877148. Thank you.

**Pull request closed without merging**
