### PR TITLE
Bug: Fix vtadmin resources

### PR DESCRIPTION
**Pull request by nianfei97**
Currently, the resources requests/limits for the vtadmin component is not reflected in the spec for vtadmin

This is because the resource spec is copied to a local variable and discarded instead of the actual container spec

Signed-off-by: Teh Nian Fei <tehnianfei@gmail.com>

### CODE REVIEW

**Review by GuptaManan100 — COMMENTED** [review]
Yep, this looks like a bug. Thankyou for catching this. Could you add a test for this in the vtorc-vtadmin test that we have. You can change the config for the spec of vtadmin and verify in the test if the resources match the ones set.

**Comment by nianfei97** [comment]
I have added a test to ensure that the vtadmin resources are set. Unfortunately, I couldn't seem to get the end2end tests running on my system, so I was unable to verify that the test works as expected.

**Comment by GuptaManan100** [comment]
@nianfei97 I verified running the test locally, it works just as expected. There was a bug fix which was merged into main recently which is required to get the CI to pass, so I have merged main into the PR. Once the tests pass I shall merge the PR.

**Review by GuptaManan100 — APPROVED** [review]

**Comment by GuptaManan100** [comment]
Thank-you for finding the bug and for your contributions @nianfei97! 🚀

**Pull request merged**
