### PR TITLE
Register the k8s topo plugin

### PR DESCRIPTION
**Pull request by jmoldow**
Signed-off-by: Jordan Moldow <jmoldow@box.com>

### CODE REVIEW

**Review by deepthi — COMMENTED** [review]
Have you been able to bring up a vitess cluster using operator and k8stopo?

**Comment by jmoldow** [comment]
@deepthi Haven't gotten that far yet, there's still some environmental factors I'm working through. But I was able to compile this, build a new Docker image, and use that Docker image to run vitess-operator successfully in a Kubernetes deployment, and apply a `VitessCluster` CRD successfully (but not one that was using k8stopo; and again, some of the environmental factors I'm working through prevent me from getting the cluster working at the moment. (But that's not a problem with vitess-operator or my change))

**Comment by jmoldow** [comment]
@deepthi Is there a concern about adding this line before we've demonstrated the full use of `k8stopo` from the operator?

**Comment by deepthi** [comment]
> @deepthi Is there a concern about adding this line before we've demonstrated the full use of `k8stopo` from the operator?

Yes, it seems incomplete (and not really useful) unless we know that it works.

**Comment by jmoldow** [comment]
@deepthi I've been able to confirm that the operator works successfully using the k8s topo. See attached.

Screen Shot 2021-07-09 at 12 56 16 PM
Screen Shot 2021-07-09 at 12 53 43 PM
Screen Shot 2021-07-09 at 12 52 48 PM
Screen Shot 2021-07-09 at 12 51 25 PM
Screen Shot 2021-07-09 at 12 50 27 PM
Screen Shot 2021-07-09 at 9 36 36 AM
Screen Shot 2021-07-09 at 9 36 15 AM

**Review by deepthi — APPROVED** [review]

**Pull request merged**
