### PR TITLE
New Feature: support ceph backup

### PR DESCRIPTION
**Pull request by JoshuaAndrew**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it:**
 support ceph backup 

**Which issue(s) this PR fixes:**
 [175](https://github.com/planetscale/vitess-operator/issues/175)

### CODE REVIEW

**Comment by JoshuaAndrew** [comment]
@enisoc  @PrismaPhonic  
Take time to review the code
Thanks!

**Comment by PrismaPhonic** [comment]
@JoshuaAndrew the code looks good to me. Have you had a chance to test it yet?

**Comment by JoshuaAndrew** [comment]
@PrismaPhonic  
Yeap, I have tested it and I will fix any related problems in time.

**Review by PrismaPhonic — APPROVED** [review]
LGTM

**Comment by PrismaPhonic** [comment]
@JoshuaAndrew thanks for this!

**Comment by PrismaPhonic** [comment]
@JoshuaAndrew I'm just now noticing there is something I missed in this review. We tend to only use `*SecretSource` if there's a valid default. You'll notice on the other location types that when we use `*SecretSource` we list what the default is if not filled in.

**Comment by PrismaPhonic** [comment]
(in general we use pointer types for optional fields where we have defaulting logic, and in that case we list in the comments what the default is if the user doesn't supply one). In this case, this actually looks like it's a non-optional field. Am I correct in assuming that?

**Comment by JoshuaAndrew** [comment]
@PrismaPhonic   Yeap.  you are correct. I had fixed that.
 [PR 179](https://github.com/planetscale/vitess-operator/pull/179)

forgive me for not responding in time.

**Pull request merged**
