### PR TITLE
Upgrade etcd version from 3.3.13 to 3.5.9

### PR DESCRIPTION
**Pull request by MrFabio**
This PR aims to upgrade the etcd version.

### CODE REVIEW

**Review by GuptaManan100 — COMMENTED** [review]
@dctrwatson Is this version of etcd okay to use?

**Review by mattlord — APPROVED** [review]
LGTM! Let's wait to hear back from @dctrwatson before merging though.

Thanks, @MrFabio ❤️

**Comment by deepthi** [comment]
Was there any testing of this at all? If you are already running with a released version of operator and upgrade to this PR, does everything still work fine? Under the covers there will be an etcd in-place upgrade.

**Comment by deepthi** [comment]
I found that the etcd project recommends taking a manual snapshot before an upgrade. We'll need to document this in the release notes.

**Pull request merged**
